services:
  user-service:
    build:
      context: .
      dockerfile: ./users-microservice/Dockerfile
    container_name: "user-service"
    ports:
      - "3000:3000"
      - "50051:50051"
    environment:
      - HOSTNAME_USER_SERVICE=user-service
      - HOSTNAME_NOTIFICATION_SERVICE=notification-service
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq

  notification-service:
    build:
      context: .
      dockerfile: ./notifications-microservice/Dockerfile
    container_name: "notification-service"
    ports:
      - "50052:50052"
    environment:
      - HOSTNAME_NOTIFICATION_SERVICE=notification-service
      - HOSTNAME_USER_SERVICE=user-service
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped
