services:
  user-service:
    build:
      context: .
      dockerfile: ./users-microservice/Dockerfile
    container_name: "user-service"
    ports:
      - "3000:3000"
      - "50051:50051"
    environment:
      - HOSTNAME_USER_SERVICE=user-service
      - HOSTNAME_NOTIFICATION_SERVICE=notification-service

  notification-service:
    build:
      context: .
      dockerfile: ./notifications-microservice/Dockerfile
    container_name: "notification-service"
    ports:
      - "50052:50052"
    environment:
      - HOSTNAME_NOTIFICATION_SERVICE=notification-service
      - HOSTNAME_USER_SERVICE=user-service
