version: "3.8"

services:
  notification-service:
    build:
      context: .
      dockerfile: ./notifications-microservice/Dockerfile
    container_name: "notification-service"
    ports:
      - "50052:50052"
