services:
  user-service:
    build:
      context: .
      dockerfile: ./users-microservice/Dockerfile
    container_name: "user-service"
    ports:
      - "3000:3000"
      - "50051:50051"

  notification-service:
    build:
      context: .
      dockerfile: ./notifications-microservice/Dockerfile
    container_name: "notification-service"
    ports:
      - "50052:50052"
